name: Check Dependencies
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * MON" # every Monday at 6:00 AM UTC
env:
  NODE_VERSION: 20
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run audit
        uses: oke-py/npm-audit-action@v2
        with:
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
